#!/bin/bash

rm temp -rf
mkdir temp
cp install.rdf temp
cp theme temp -r
cp options temp -r
cp icon.png temp/theme
cp icon.png temp/options
cd temp

#Create Freedesktop theme
mkdir fd
cp -R theme fd/theme
cp install.rdf fd
sed -E "s/((INTERNAL_)?NAME|THEME_(ID|DESC))/\0_FD/g" -i "fd/theme/install.rdf" "fd/theme/chrome.manifest" "fd/install.rdf"

#Substitute variables
FILES=`find . -type f -exec grep -Iq . {} \; -and -print`
while read LINE; do
    if [[ $LINE != [A-Z]* ]]; then
        continue
    fi
    LINE1=`echo $LINE | grep -oE "^[^=]+"`
    LINE2=`echo $LINE | grep -oE "[^=]+$"`
    sed "s|\$$LINE1|$LINE2|g" -i $FILES
    eval "$LINE1=\"$LINE2\""
done < "../config.txt"

#Output icons
cd theme
FILES=`find . -name "*.css"`
for F in $FILES; do
  N=`grep STOCK-ICON $F -c`
  if (( N > 0 )); then
    echo $F
    echo " $N"
  fi
done

#Substitute icons
for F in $FILES; do
    ORIG="%STOCK-ICON ([^ ]+) ([^ ]+) ([0-9]+b?)( (disabled))?"
    NEW1="moz-icon:\/\/stock\/\1?size=\3\&state=\5"
    NEW2="moz-icon:\/\/stock\/\2?size=\3\&state=\5"
    sed -E "s/$ORIG/$NEW1/g" -i "$F"
    sed -E "s/$ORIG/$NEW2/g" -i "../fd/theme/$F"
    ORIG="%CUSTOM-ICON ([^ ]+) ([0-9]+b?)( (disabled))?"
    NEW1="chrome:\/\/global\/skin\/icons\/\2x\2\/\1.png"
    NEW2="moz-icon:\/\/stock\/\1?size=\2\&state=\4"
    sed -E "s/$ORIG/$NEW1/g" -i "$F"
    sed -E "s/$ORIG/$NEW2/g" -i "../fd/theme/$F"

    sed -E "s/16bx16b/16x16/g" -i "$F" "../fd/theme/$F"
    sed -E "s/size=16b/size=button/g" -i "$F" "../fd/theme/$F"
    sed -E "s/size=16/size=menu/g" -i "$F" "../fd/theme/$F"
    sed -E "s/size=24/size=toolbar/g" -i "$F" "../fd/theme/$F"
    sed -E "s/size=48/size=dialog/g" -i "$F" "../fd/theme/$F"
    sed -E "s/&state=\"/\"/g" -i "$F" "../fd/theme/$F"

    sed -E "s/%DISABLED-OPACITY/0.5/g" -i "$F"
    sed -E "s/%DISABLED-OPACITY/1.0/g" -i "../fd/theme/$F"
done
cd ..

cp -R options fd

#Package
THEME_JAR="theme.jar"
OPTIONS_JAR="options.xpi"
NAME="gnomerunnergtk-revived-$VERSION-sm-linux.xpi"
NAME_FD="gnomerunnerfd-revived-$VERSION-sm-linux.xpi"
cd theme
zip ../$THEME_JAR * -qr
cd ../options
zip ../$OPTIONS_JAR * -qr
cd ..
zip ../$NAME $THEME_JAR $OPTIONS_JAR install.rdf -q
cd fd/theme
zip ../$THEME_JAR * -qr
cd ../options
zip ../$OPTIONS_JAR * -qr
cd ..
zip ../../$NAME_FD $THEME_JAR $OPTIONS_JAR install.rdf -q
cd ../..
