#!/bin/bash

rm temp -rf
mkdir temp
cp install.rdf temp
cp theme temp -r
cp options temp -r
cp icon.png temp/theme
cp icon.png temp/options
cd temp

#Create Freedesktop theme
mkdir fd
cp -R theme fd/theme
cp install.rdf fd
sed -E "s/((INTERNAL_)?NAME|THEME_(ID|DESC))/\0_FD/g" -i "fd/theme/install.rdf" "fd/theme/chrome.manifest" "fd/install.rdf"

#Substitute variables
while read LINE; do
    if [[ $LINE != [A-Z]* ]]; then
        continue
    fi
    LINE1=`echo $LINE | grep -oE "^[^=]+"`
    LINE2=`echo $LINE | grep -oE "[^=]+$"`
    sed "s|\$$LINE1|$LINE2|g" -i `find . -name "*.rdf"` `find . -name "*.xul"` `find . -name "*.js"` `find . -name "*.css"` `find . -name "*.manifest"` `find . -name "*.dtd"`
    eval "$LINE1=\"$LINE2\""
done < "../config.txt"

#Generate menu icon rules
ORIG="\%NATIVE-ICON (.*) (.*) (.*)"
NEW="\3:-moz-system-metric(images-in-menus) > label {\n"
NEW+="    padding-left: 21px !important;\n"
NEW+="    margin-left: 0px !important;\n"
NEW+="}\n\n\3 {\n"
NEW+="    list-style-image: url(\"%STOCK-ICON \1 \2 16\") !important;\n"
NEW+="}\n\n\3:-moz-system-metric(images-in-menus) > label {\n"
NEW+="    background: url(\"%STOCK-ICON \1 \2 16\") 0% 50% no-repeat !important;\n"
NEW+="}\n\n\3:-moz-system-metric(images-in-menus)[disabled=\"true\"] > label {\n"
NEW+="    background: url(\"%STOCK-ICON \1 \2 16 disabled\") 0% 50% no-repeat !important;\n"
NEW+="}\n"
sed -E "s|$ORIG|$NEW|g" -i `find . -name "*.css"`

ORIG="\%ICON \"(.*)\" (.*)"
NEW="\2:-moz-system-metric(images-in-menus) > label {\n"
NEW+="    padding-left: 21px !important;\n"
NEW+="    margin-left: 0px !important;\n"
NEW+="}\n\n\2 {\n"
NEW+="    list-style-image: url(\"\1\") !important;\n"
NEW+="}\n\n\2:-moz-system-metric(images-in-menus) > label {\n"
NEW+="    background: url(\"\1\") 0% 50% no-repeat !important;\n"
NEW+="}\n"
sed -E "s|$ORIG|$NEW|g" -i `find . -name "*.css"`

#ORIG="\%NATIVE-ICON (.*) (.*)"
#NEW="\2 {\n"
#NEW+="    -moz-binding: url(\"chrome://global/content/bindings/menu.xml#menuitem-iconic\") !important;\n"
#NEW+="    list-style-image: url(\"moz-icon://stock/\1?size=menu\") !important;\n"
#NEW+="}\n"
#sed -E "s|$ORIG|$NEW|g" -i `find . -name "*.css"`

#ORIG="\%ICON \"(.*)\" (.*)"
#NEW="\2 {\n"
#NEW+="    -moz-binding: url(\"chrome://global/content/bindings/menu.xml#menuitem-iconic\") !important;\n"
#NEW+="    list-style-image: url(\"\1\") !important;\n"
#NEW+="}\n"
#sed -E "s|$ORIG|$NEW|g" -i `find . -name "*.css"`

#Substitute icons
cd theme
FILES=`find . -name "*.css"`
for F in $FILES; do
    ORIG="%STOCK-ICON ([^ ]+) ([^ ]+) ([0-9]+b?)( (disabled))?"
    NEW1="moz-icon:\/\/stock\/\1?size=\3\&state=\5"
    NEW2="moz-icon:\/\/stock\/\2?size=\3\&state=\5"
    sed -E "s/$ORIG/$NEW1/g" -i "$F"
    sed -E "s/$ORIG/$NEW2/g" -i "../fd/theme/$F"
    ORIG="%CUSTOM-ICON ([^ ]+) ([0-9]+b?)( (disabled))?"
    NEW1="chrome:\/\/global\/skin\/icons\/\2x\2\/\1.png"
    NEW2="moz-icon:\/\/stock\/\1?size=\2\&state=\4"
    sed -E "s/$ORIG/$NEW1/g" -i "$F"
    sed -E "s/$ORIG/$NEW2/g" -i "../fd/theme/$F"

    sed -E "s/16bx16b/16x16/g" -i "$F" "../fd/theme/$F"
    sed -E "s/size=16b/size=button/g" -i "$F" "../fd/theme/$F"
    sed -E "s/size=16/size=menu/g" -i "$F" "../fd/theme/$F"
    sed -E "s/size=24/size=toolbar/g" -i "$F" "../fd/theme/$F"
    sed -E "s/size=48/size=dialog/g" -i "$F" "../fd/theme/$F"
    sed -E "s/&state=\"/\"/g" -i "$F" "../fd/theme/$F"

    sed -E "s/%DISABLED-OPACITY/0.5/g" -i "$F"
    sed -E "s/%DISABLED-OPACITY/1.0/g" -i "../fd/theme/$F"
done
cd ..

cp -R options fd

#Package
THEME_JAR="theme.jar"
OPTIONS_JAR="options.xpi"
NAME="gnomerunnergtk-revived-$VERSION-sm-linux.xpi"
NAME_FD="gnomerunnerfd-revived-$VERSION-sm-linux.xpi"
cd theme
zip ../$THEME_JAR * -qr
cd ../options
zip ../$OPTIONS_JAR * -qr
cd ..
zip ../$NAME $THEME_JAR $OPTIONS_JAR install.rdf -q
cd fd/theme
zip ../$THEME_JAR * -qr
cd ../options
zip ../$OPTIONS_JAR * -qr
cd ..
zip ../../$NAME_FD $THEME_JAR $OPTIONS_JAR install.rdf -q
cd ../..
